### PR TITLE
fixes #56: indent cases inside switch statements

### LINKED ISSUE #56: cases in switch statements not indented
prettier is printing cases at the same indentation level as their parent switch statement. I indent cases inside a switch statement.

Now:

```js
switch (something) {
case "foo":
  // ...
  break;
case "bar":
  // ...
  break;
}
```

Ideally:

```js
switch (something) {
  case "foo":
    // ...
    break;
  case "bar":
    // ...
    break;
}
```

### PR DESCRIPTION
**Pull request by michaelficarra**
Fixes #56.

### CODE REVIEW

**Comment by bakkot** [comment]
Note that this produces

```js
switch (something) {
  case "foo": {
      iAmIndentedTwice;
    }
}
```

**Comment by jlongster** [comment]
> Note that this produces

This was actually a problem before this PR. I think in the `SwitchCase` we only need to add an `indent` if the body is not a BlockStatement, because I think the BlockStatement adds an indentation level.

**Comment by jlongster** [comment]
Everyone on twitter said that wanted this, so 👍  I don't indent them but I don't really care.

**Comment by markerikson** [comment]
Can't speak for anyone else, but yes, I personally have always indented my `case` statements:

```js
switch(type) {
    case A: {
        // stuff
        break;
    }
    case B: {
        // stuff
        break;
    }
    default : return state;
}
```

**Comment by jlongster** [comment]
@michaelficarra Are you interested in trying to fix the indentation bug? I think [this indent](https://github.com/jlongster/prettier/blob/master/src/printer.js#L1024) only needs to be there if `n.consequent[0].type !== "BlockStatement`.

**Comment by bakkot** [comment]
> I think in the SwitchCase we only need to add an indent if the body is not a BlockStatement

The `case` itself still needs to be indented, it's just that the block doesn't.

**Comment by michaelficarra** [comment]
@jlongster Sure, as a separate PR.

**Comment by jlongster** [comment]
Awesome, thanks!

**Pull request merged**
