### PR TITLE
Remove parens around AwaitExpression in ternary

### LINKED ISSUE #313: Unneeded parenthesis around await in ternary
```js
async function f() {
  const result = typeof fn === 'function' ? await fn() : null;
}
```

outputs

```js
async function f() {
  const result = typeof fn === "function" ? (await fn()) : null;
}
```

but the parenthesis is not needed.

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22async%20function%20f()%20%7B%5Cn%20%20const%20result%20%3D%20typeof%20fn%20%3D%3D%3D%20'function'%20%3F%20await%20fn()%20%3A%20null%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

### PR DESCRIPTION
**Pull request by existentialism**
Fixes #313

### CODE REVIEW

**Comment by vjeux** [comment]
Thanks :)

**Comment by LegNeato** [comment]
Why not remove the old option now? It is still early, and people were warned about breakage...

**Comment by vjeux** [comment]
I'm not sure I follow your comment. This is not a breaking change.

The stance on prettier on parenthesis is that we should only output the ones that are necessary for your code to parse the same way as inputted.

In this case, we did not need this parenthesis to disambiguate so we shouldn't output it.

Is there something I missed?

**Comment by vjeux** [comment]
Maybe you are talking about another issue with --flow-parser. If that's the case, there are currently a bunch of editor integrations that exist, it's annoying to have to track them down and ask them to update the option right now.

The cost of supporting the previous option is very low and if we stop documenting the old option, no new plugin is going to use it and the old ones are going to update at some point and we can just drop that option later which only involves removing a few lines of code.

I feel like it's a better way of handling out breaking changes. It's a small amount of work for the maintainer but no user gets frustrated by having something that breaks under them. Even if it's alpha, it's still a really shitty experience.

**Pull request merged**
