### PR TITLE
Put decorators on the same line

### LINKED ISSUE #325: Decorators for MobX put on separate lines
I understand that class decorators are usually put on their own line above the class, however the standard style with MobX annotations within a class is to put them on the same line as what they annotate. [Example](https://mobx.js.org/refguide/observable-decorator.html):

screen shot 2017-01-19 at 15 25 22

Currently prettier splits all the lines that have decorators, making it look very messy.

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22import%20%7Bobservable%7D%20from%20%5C%22mobx%5C%22%3B%5Cn%5Cnclass%20OrderLine%20%7B%5Cn%20%20%20%20%40observable%20price%3Anumber%20%3D%200%3B%5Cn%20%20%20%20%40observable%20amount%3Anumber%20%3D%201%3B%5Cn%5Cn%20%20%20%20constructor(price)%20%7B%5Cn%20%20%20%20%20%20%20%20this.price%20%3D%20price%3B%5Cn%20%20%20%20%7D%5Cn%5Cn%20%20%20%20%40computed%20get%20total()%20%7B%5Cn%20%20%20%20%20%20%20%20return%20this.price%20*%20this.amount%3B%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

### PR DESCRIPTION
**Pull request by vjeux**
Mobx is the only popular JavaScript library that I know about which uses decorators. They put things on the same line so we should follow their conventions.

The logic implemented here is the following: if there is one decorator, it's on the same line. If there is more than one, they are each on their own line.

Fixes #325

### CODE REVIEW

**Comment by vramana** [comment]
redux `connect` can also be used with a decorator. But the decorator is placed above the class.

**Comment by vjeux** [comment]
@vramana good call! It seems like redux connect takes arguments. We likely don't want decorators with arguments to be inlined. Let me encode this rule as well!

**Comment by vjeux** [comment]
Done, now it has to be a single decorator AND just an identifier to be inlined.

I also tried to enable flow decorator support but it only supports half of the decorators in the tests and has a different AST structure, so it's not worth using it.

**Comment by jlongster** [comment]
Thanks, looks good!

**Comment by egeozcan** [comment]
Is there a possibility to make this configurable? I personally really dislike decorators being in the same line. Makes it very hard to browse the class properties.

```typescript
  @Entity("Todos")
  export class Todo implements ITodo {
    @PrimaryGeneratedColumn("uuid") public id?: string;
    @Column() public text: string;
    @Column() public completed: boolean;
  }
```

**Comment by jrylan** [comment]
@jlongster @vjeux @vramana I agree highly with @egeozcan -- would love to see this be a configurable value. If I submit a PR, would the team be up for merging it or is everyone set on keeping things as is?

**Comment by JoshuaKGoldberg** [comment]
+1. This is very annoying, especially with [Inversify](http://inversify.io).

```typescript
public constructor(
    @inject(MyStoreStore) public readonly myStore: MyStore,
    @inject(InjectionTypes.StyleProvider) public readonly styleProvider: IStyleProvider,
) { }
```

Relevant issue: #1974

**Comment by duailibe** [comment]
@JoshuaKGoldberg Please open a new issue, filling the template

**Pull request merged**
