### PR TITLE
Add reference to Prettier Sublime Text plug-in

### PR DESCRIPTION
**Pull request by jonlabelle**
[Sublime Text editor plug-in](https://github.com/jonlabelle/SublimeJsPrettier) for Prettier

### CODE REVIEW

**Comment by demoneaux** [comment]
You might want to look at #17 first. There are a few others with other separate Sublime Text plugins already, which are in the process of merging to create a canonical Sublime Text plugin.

**Comment by jonlabelle** [comment]
Ahh, okay. Though did already submit the [pull request](https://github.com/wbond/package_control_channel/pull/6076) to Package Control for [my plug-in](https://github.com/jonlabelle/SublimeJsPrettier); though it's pending approval. I think the [other one](https://github.com/danreeves/sublime-prettier) is still a WIP.

**Comment by demoneaux** [comment]
Maybe you could discuss with @danreeves and @jlangston at #17 and decide on which project to continue working on first :)

**Comment by jlongster** [comment]
Yeah, please collaborate in #17. Sorry things haven't converged yet but I'd like to link to only one package for each editor (possibly with an "extra" section if there a other cool integrations, but would still like only one per editor for the "straightforward" integration).

I'll merge a PR that is 👍 by everyone in #17. For now, closing.

**Pull request closed without merging**
