### PR TITLE
Add --run-in-band to travis

### PR DESCRIPTION
**Pull request by vjeux**
Hopefully it'll fix spurious errors.

### CODE REVIEW

**Comment by vjeux** [comment]
The test run had `--runInBand` properly working.

**Comment by vjeux** [comment]
With
image


Without
image

So, it doesn't dramatically decrease the runtime.

**Comment by jlongster** [comment]
Nice!

**Comment by jlongster** [comment]
Guess we can run travis and circle a the same time for a while and see what we think.

**Pull request merged**
