### PR TITLE
[WIP] Fix flow annotation parenthesis

### LINKED ISSUE #719: Flow Typecast Comments
In flow, you can typecast with the following,

```js
(obj: Class).property
```

You can also do this with comments,

```js
(obj /*: Class */).property
```

However, this gets transformed into,

```js
obj /*: Class */.property
```

Both are syntactically valid, but only one is recognised by flow. Maybe we'd just want to check comments that start with `:`?

Happy to help if you decide what direction we should go!

# Edit

Also,

```js
const x = (input /*: string */) /*: string */ => {};
// to
const x = (input /*: string */ /*: string */) => {};
```

### PR DESCRIPTION
**Pull request by vjeux**
The implementation is not super elegant but it seems to work.

Fixes #719

### CODE REVIEW

**Comment by vjeux** [comment]
Actually, it doesn't work

```js
const x = ((input /*: string */) /*: string */) => {};
```

it outputs invalid JavaScript. I'm not really sure how to fix this :(

**Comment by vjeux** [comment]
One idea is to keep this logic and also add some extra logic: if you attach a comment to an argument and there's already an comment, then attach it as the return value...

**Comment by jlongster** [comment]
Adding semantic value to comments is kinda crazy now that I know how hard it is to make sure comments are in the right place... Going to look at the other PRs for now and come back to this.

**Comment by vjeux** [comment]
We need to figure out a better solution, right now it can generate invalid code :(

**Pull request closed without merging**
