### PR TITLE
Fix await parenthesis

### LINKED ISSUE #164: Incorrectly removing parenthesis around await expression
Before:

```js
    assert.equal(
      (await driver.browser.activeWindow.navigator.getUrl()).substr(-7),
      '?q=1357',
    );
```

After:

```js
assert.equal(await driver.browser.activeWindow.navigator.getUrl().substr(-7), '?q=1357');
```

Before this change, the expression being awaited was:

```js
driver.browser.activeWindow.navigator.getUrl()
```

but after it is:

```js
driver.browser.activeWindow.navigator.getUrl().substr(-7)
```

### PR DESCRIPTION
**Pull request by vjeux**
This is the first time I'm adding something inside of fast-path so I'm not sure if it's correct, but it seems more correct than before!

Fixes #164

### CODE REVIEW

**Comment by existentialism** [comment]
:+1: was just about to post pretty much the same fix!

**Comment by vjeux** [comment]
@existentialism: oh noes! There's still a bunch more things to be fixed if you are interested. Flag yourself on an issue so we don't work on the same one :)

**Comment by existentialism** [comment]
@vjeux oh no worries at all, will def work on others!

**Comment by jlongster** [comment]
Awesome, thanks!

**Pull request merged**
