### PR TITLE
add travis config and add yarn support

### PR DESCRIPTION
**Pull request by knowbody**

### CODE REVIEW

**Comment by vramana** [comment]
Probably yarn.lock should also be added .npmignore?

**Comment by jlongster** [comment]
On that note, `tests` should probably be as well.

**Comment by knowbody** [comment]
ok let me fix it

**Comment by jlongster** [comment]
Can you also change instances of `npm` in the readme to `yarn`, and in the install docs add a note that you can use `npm` as well if you like but we are defaulting to yarn?

**Comment by knowbody** [comment]
sure

**Comment by knowbody** [comment]
@vramana @jlongster added what you suggested, please review

**Comment by jlongster** [comment]
Absolutely perfect 🌟

**Pull request merged**
