### PR TITLE
Break nested calls

### LINKED ISSUE #513: Nested function wrappers indentation issue
version: 0.13.1

formatting issue:
screen shot 2017-01-29 at 8 49 48 pm

how it should look like:
screen shot 2017-01-29 at 8 51 43 pm

### PR DESCRIPTION
**Pull request by vjeux**
If there's a break inside of a call, we want to force it in the group, otherwise it may get the indentation wrong. See the real-world use case in #513

Fixes #513

### CODE REVIEW

**Comment by jlongster** [comment]
This basically reverts https://github.com/jlongster/prettier/pull/470, and I think it's why I removed it from the whitelist before. What's happening is since the last arg (the only one here) is a call it allows that to wrap. This undoes that change and it seems confusing to have two conflicing heuristics.

Is there something different that this does that removing `CallExpression` from the whitelist doesn't?

**Comment by vjeux** [comment]
So now we know! I'll try to figure out something to accomodate both use cases.

**Comment by vjeux** [comment]
I'm not sure that it is a revert of #470, if you look at that pull request, I added a test and the test still passes in this one. So it seems like both fixes are not incompatible. Would you mind doing another review of this? I think this is the right fix.

**Comment by jlongster** [comment]
Yep, you are right. It's good to know to why I removed `CallExpression` before, but this is the right fix that allows things to break then they can. These 2 PRs can act as documentation if we ever need to look it up again.

Thanks for looking into it and finding the right fix!

**Comment by amasad** [comment]
awesome! Love how fast you guys are moving -- release soon? 👀

**Comment by vjeux** [comment]
@amasad I'm thinking of doing a release tomorrow.

**Comment by amasad** [comment]
@vjeux OK, I'll probably use master because I want to see if there are any more bugs running this on our codebase

**Pull request merged**
