### PR TITLE
Exit with an error if an unknown CLI option is passed

### PR DESCRIPTION
**Pull request by lydell**

### CODE REVIEW

**Comment by vjeux** [comment]
I'm not sure if it's a good idea to exit with an error. If we add a new stylistic flag in the future, then callers will have to make sure that they are calling a version of prettier otherwise it's going to completely fail instead of gracefully degrading.

What about just putting a message on stderr (with console.error). This way you know you did something that's not correct but it doesn't stop you.

**Comment by lydell** [comment]
Good point! I've pushed the change.

**Comment by vjeux** [comment]
Thanks!

**Comment by vjeux** [comment]
FYI, I checked and console.warn is indeed written on stderr.

image

**Pull request merged**
