### PR TITLE
[RFC] Always expand objects if contained in another object or array

### LINKED ISSUE #74: Consistency in lists/objects
Thanks for your work, I'm VERY interested in something that deals with formatting in my place =)

One thing that struck me upon trying it out tonight, though, was that it does not handle "siblings" consistently. That is, given a list of, say, { id, name } objects; if one of them has a name large enough to reach the line limit, then this object, and this object alone, will be printed over 4 lines, while its siblings will be printed on 1 line. The "exploded" one will have a trailing comma, too, while obviously the one-liners will not.

Original `test.js`:
```
const myList = [
  {
    id: 0,
    name: 'Short',
  },
  {
    id: 1,
    name: 'Short Too',
  },
  {
    id: 3,
    name: 'Too Long For Your Line Width',
  },
];
```

Result (`$ prettier --bracket-spacing --trailing-comma --print-width 40 test.js`):
```
const myList = [
  { id: 0, name: "Short" },
  { id: 1, name: "Short Too" },
  {
    id: 3,
    name: "Too Long For Your Line Width",
  },
];
```

I think that in this case, the original is the better code: it's consistent, easily readable and parsable, at the only cost of taking a lot of vertical space (scrolling is cheap, though).

EDIT: removed JSX example and reworded the issue as per @vramana's comment.

### PR DESCRIPTION
**Pull request by vjeux**
The flow tests look really bad with it but the more real world tests feel much better. I think we'll have to run that on a real codebase and see how it feels.

Fixes #74

### CODE REVIEW

**Comment by jlongster** [comment]
I wonder if we added one more condition to the heuristic: there are 2 or more properties in the object. I realized that we would break cases like `{ foo: { bar: { baz: 5 } } }` which look nice collapsed, but once you get more than one it makes sense to expand them. What do you think?

**Comment by yamafaktory** [comment]
@vjeux this doesn't have any effect with the Flow parser, e.g.:

```js
const a = {b: 5,c: 4,d: {e,f: {}}};
```

outputs (Babylon):

```js
const a = {
  b: 5,
  c: 4,
  d: {
    e,
    f: {}
  }
};
```

with Flow:

```js
const a = { b: 5, c: 4, d: { e, f: {} } };
```

**Comment by vjeux** [comment]
After thinking more about it, I think that the key property we want is consistency between all the objects of an object/array. So, if there's one object in an object that would be split, then we need to split all of them.

I don't think that the current IR supports this kind of behavior but I think that it would solve a lot of the problems with objects expansion.

**Comment by jlongster** [comment]
Yeah, that's too complicated for the printer. That would require something like browser's "reflow" capability where it sees something doesn't fit and can arbitrarily reflow any part of the output. It's not only complicated but could worsen performance.

It's going to be easier to have a heuristic that we can apply statically at IR-generation time.

**Comment by vjeux** [comment]
We need to think more about this problem. I don't think that this idea is going to work out well.

**Pull request closed without merging**
