### PR TITLE
optional break after member lookup

### PR DESCRIPTION
**Pull request by despairblue**
This concerns #212. More information is in [my comment there](https://github.com/jlongster/prettier/issues/212#issuecomment-272693530).

I don't like the way comments at the end of lines trigger this change. Maybe they should be lifted to the top. 🤔

### CODE REVIEW

**Comment by vjeux** [comment]
This is the result of this pull request on the nuclide codebase: https://gist.github.com/vjeux/4973a6290cd6badd4ef33b30bc2bce9c

**Comment by despairblue** [comment]
Whoops. 😓  

Yeah, it's probably to eager. It should try that only if the other expansions are not enough. What do you think?

**Comment by jlongster** [comment]
@despairblue Thanks a lot for this. My gut feeling, which I mentioned in #212, is that this is going to introduce several awkward situations when combined with other syntaxes. Take a look at the first diff in @vjeux's example:

```patch
-      return Observable.concat(
-        Observable.of(editor),
-        this._newProviderEvents.mapTo(editor)
-      );
+      return Observable
+        .concat(Observable.of(editor), this._newProviderEvents.mapTo(editor));
```

If we enable breaking on `.`, no matter how do it, the above is going to happen. This is because it exists before the method call. We cannot try inner expansions first because it would be horrible for performance and adds a *lot* of complexity. We do it in a very few other uses cases but it makes the code a lot harder to understand (I think in 2 places we use `conditionalGroup` for this). And I think even if we tried it, we would get mostly back to where we are now. It's just not worth the complexity.

The maximum line width at the end of the say is a suggestion. The printer will happily print past it if there's nothing it can do. There's only so much we can do to break things up. If the user has a really long lookup, they should break it up into multiple lines. I think in all of the edge cases we are trying to fix here, the user should just fix their code if they really don't want it all on one line. I think forcing them to introduce intermediate variables could actually help clarify code.

As for comments, yeah, inline comments are very weird and will do things like trigger breaking at certain points. The user can manually move them up if they don't want that.

I don't think this is the right direction to take. `.` is such a pervasive operator in JS that breaking on it introduces a whole new range of formatting situations that we have to handle and I don't think we should go through the work to do that. You original real code looks fine to me, even if it crosses the threshold:

```js
function* sendMail() {
  try {
    const pdfStream = yield contractsService.getLandlordContractStreamFromBooking(
      booking
    );
  } catch (error) {
    report(error);
  }
}
```

The great thing about this formatter compared to eslint is you don't really have to worry about it when this happens. You just have one line that's pretty long. That's OK. We won't consistently warn you about it like eslint and force you to disable the max-len rule just for that line or anything. That line can just be a little longer :)

**Comment by despairblue** [comment]
@jlongster thank you for taking the time to explain this in so much detail :) 

That choice is understandable. I try to use prettier on our codebase @wunderflats and there are some other edge cases (chai assertions e.g.). I'll open new issues with ideas.

**Pull request closed without merging**
