### PR TITLE
Accept globs and lists of files

### LINKED ISSUE #58: Globs aren't supported?
Running `prettier --write --single-quote src/*.js` or when using with `package.json` like this:

```json
{
  "scripts": {
    "prettify": "prettier --write --single-quote",
    "prettify:src": "npm run prettify -- src/*.js *.js",
  }
}
```

it only processes the first file that the glob pattern is resolving. In my case running `npm run prettify:src` producing the following command:

```
prettier --write --single-quote "src/getDataTransferItems.js" "src/getDataTransferItems.spec.js" "src/index.js" "src/index.spec.js" "testSetup.js" "wallaby.config.js" "webpack.config.js"
```

But only `src/getDataTransferItems.js` got processed.

### PR DESCRIPTION
**Pull request by okonet**
This PR implements support for glob patterns. 

ATM prettier only processes the first file if a list of files is given in arguments.

This will allow running prettier with https://github.com/okonet/lint-staged

Closes #58

### CODE REVIEW

**Comment by michaelficarra** [comment]
Why did you rename the binary? That's a breaking API change.

**Comment by sapegin** [comment]
@michaelficarra Binary is the same, but editing .js files are easier.

**Comment by okonet** [comment]
@michaelficarra I didn't break it. The binary will have the same name when installed with npm.

**Comment by michaelficarra** [comment]
Oh, I wasn't aware of that npm behaviour.

**Comment by jlongster** [comment]
I was wanting it to work this way, thanks!

**Pull request merged**
