### PR TITLE
Switch  to ES6 code style everywhere and specify NodeJS & npm engines.

### PR DESCRIPTION
**Pull request by yamafaktory**
Hi @jlongster and thanks a lot for this awesome tool!

For consistency, I've updated the complete source code to be "_ES6-ified_" (`let` / `const` instead of `var`, arrow functions for better readability) and specified the NodeJS (latest recommended LTS) & npm engines in the package.json file in order to avoid any bad user experience.

### CODE REVIEW

**Comment by yamafaktory** [comment]
I should have checked the TravisCI file before... You can drop this PR as it involves unsupported changes if you want to stick with NodeJS v4. Sorry for the inconvenience 😞

**Comment by demoneaux** [comment]
Yep, I believe we intend to support Node.js v4+.

**Comment by vramana** [comment]
Yes. We intend to support Node v4

**Comment by jlongster** [comment]
Yeah, I think that's why we needed to add "use strict" at the top of all files so we had access to const/let in node 4. We also have to avoid destructuring, etc.

Thank you doing all this work. Unfortunately I don't think we should accept it since we want older node support, and I don't really want to take on the complexity of a build step. Honestly, it doesn't seem to affect me very much even though I'm used to coding with ES6 constructs all the time. The patterns of this code are very well established and it's pretty easy to work on this codebase without the ES6 features.

At some point in the future, I'm open to setting up a babel compile step and figuring all that out. But for now since everything already works in node 4 let's keep it that way.

I hope you didn't spend too much time on this! Feel free to look through the issues and find something else to fix.

**Pull request closed without merging**
