### PR TITLE
Add semicolons to `export` declarations.

### LINKED ISSUE #22: Don't remove semicolon from exports
#### expected behavior:

```js
export default MyComponent;
```

#### current behavior:

```js
export default MyComponent
```

### PR DESCRIPTION
**Pull request by demoneaux**
Closes #22.

### CODE REVIEW

**Comment by knowbody** [comment]
LGTM!

**Comment by jlongster** [comment]
Awesome, thanks so much!

**Comment by calvinl** [comment]
Did this fix make it into `0.0.7`? I'm using `prettier-atom` 0.0.7, and it's stripping the semicolon from this statement:

```
export default connect(mapStateToProps)(MyComponent)
```

**Comment by demoneaux** [comment]
I believe this did make it into 0.0.7, but this case doesn't seem to be covered by the current code. I'll look into it tonight and see if there's any fixes to do.

**Comment by jlongster** [comment]
Yeah, that case doesn't work for some reason:

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22export%20default%20connect(mapStateToProps)(MyComponent)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

Can you file a new bug?

**Comment by calvinl** [comment]
Thanks guys -- I'll file the issue.

**Comment by existentialism** [comment]
@calvinl pushed a fix => https://github.com/jlongster/prettier/pull/287

**Pull request merged**
