### PR TITLE
Add option for putting > on the last line in jsx

### LINKED ISSUE #654: JSX opening element closing tag gets moved to a new line
If you have a line of JSX that is over printWidth, something like:

```js
const El = (<span width="1" height="2">x</span>)
```

For the sake of reproducing the issue assume the printWidth is set to 20 but this reproduces anytime the line needs to break for JSX. Then the code is formatted as:

```js
const El = (
    <span
        width="1"
        height="2"
    >
        x
    </span>
);
```

Notice the span `>` being placed on a new line by itself. 
Again this wastes lots of vertical space whenever you have many tags in a component. Instead a better option would be either to make it configurable or to place it on the same line as the last prop, eg:

```js
const El = (
    <span
        width="1"
        height="2" >
        x
    </span>
);
```

### PR DESCRIPTION
**Pull request by vjeux**
Feel free to suggest a better name for the option. Otherwise it works great :)

Fixes #654

### CODE REVIEW

**Comment by jlongster** [comment]
What about `jsxBracketSameLine`? Or `jsxBracketLastLine`. Or `jsxBracketNewline` and it would default to `true` (not preferred).

I think I like `jsxBracket*` because it's emphasizes that it's about the bracket. I'm not sure "last line" is very descriptive when reading the options. Although none of these are great, "same line" I think connects better with what people are thinking probably, i.e. "I wish it would put it on the same line as my attributes"

Anyone else have other ideas?

**Comment by vjeux** [comment]
I like `jsxBracketSameLine`

**Comment by joecritch** [comment]
@vjeux This option feels very specific, when compared to the others. What was the reasoning behind it?

**Comment by vjeux** [comment]
@joecritch This is the way we write JSX at Facebook and an existing big source of drama internally. I didn't want people discussing this particular point when I'm pushing for prettier.

**Pull request merged**
