### PR TITLE
Do not put spaces on empty for loop

### PR DESCRIPTION
**Pull request by vjeux**
```js
for (;;) {
```

instead of

```js
for (; ; ) {
```

### CODE REVIEW

**Comment by jlongster** [comment]
Perfect, I meant to follow-up with this a long time ago!

**Comment by jlongster** [comment]
I'm very confused how this worked and passed CI. On my machine I see:

```js
    /Users/james/projects/prettier/src/printer.js: Duplicate declaration "body"
        869 |     return group(concat(parts));
        870 |   case "ForStatement":
      > 871 |     const body = adjustClause(path.call(print, "body"), options);
            |           ^
        872 |
        873 |     if (!n.init && !n.test && !n.update) {
        874 |       return concat([
```

This is because the case statement isn't wrapped in a block. An easy fix, but was it running on a version of node that doesn't error or something?

**Comment by jlongster** [comment]
I opened a fix: https://github.com/jlongster/prettier/pull/172

**Comment by vjeux** [comment]
Hmm, weird that it passed CI indeed. I just pulled master and it's not working anymore. I moved the code without re-testing it. Sorry about that!

**Comment by jlongster** [comment]
No worries. It's a downside of using `case` but not a big deal. My bigger concern is how this passed. I almost released this. We'll see if it happens again!

**Pull request merged**
