### PR TITLE
Add newline to EOF.

### LINKED ISSUE #55: Doesn't respect new lines at EOF
Not sure if it's "by design" but it strips the new lines at end of files.

2017-01-10 at 20 48

### PR DESCRIPTION
**Pull request by demoneaux**
Closes #55.

Note: I didn't update the snapshots as all the tests were affected, and I didn't want to cause any major issues while merging.

### CODE REVIEW

**Comment by jlongster** [comment]
This looks good. I actually had this code before but removed it because I thought that my code to keep blank lines around fixed it, but it doesn't. Let's try this.

I think we should always just go ahead and regenerate the snapshots. This shouldn't conflict with anything because it only affects the end of the files. I will merge and regenerate myself however.

**Comment by erictse** [comment]
Does this work? I have 0.11.0 installed on the command line as well as prettier-atom, and I'm still seeing newlines disappear from end of files.

**Comment by KSuttle-cng** [comment]
But can this ignore empty files instead of writing a newline?

**Comment by suchipi** [comment]
@KSuttle-cng please open a new issue to discuss the proposed change.

**Comment by KSuttle-cng** [comment]
https://github.com/prettier/prettier/issues/3440

**Pull request merged**
