### PR TITLE
Add CallExpression to the last argument expansion whitelist

### LINKED ISSUE #274: Why is `arg =>` put on a newline?
I'm looking at this prettier [formatted](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22import%20%7B%20Observable%20%7D%20from%20'rxjs%2FObservable'%3B%5Cnimport%20%7B%20replace%20%7D%20from%20'react-router-redux'%3B%5Cnimport%20*%20as%20ActionTypes%20from%20'..%2FActionTypes'%3B%5Cnimport%20%7B%20receiveUsers%20%7D%20from%20'..%2Factions'%3B%5Cnimport%20%7B%20ajax%20%7D%20from%20'rxjs%2Fobservable%2Fdom%2Fajax'%3B%5Cn%5Cnexport%20default%20function%20searchUsers(action%24)%20%7B%5Cn%20%20return%20action%24.ofType(ActionTypes.SEARCHED_USERS)%5Cn%20%20%20%20.map(action%20%3D%3E%20action.payload.query)%5Cn%20%20%20%20.filter(q%20%3D%3E%20!!q)%5Cn%20%20%20%20.switchMap(q%20%3D%3E%5Cn%20%20%20%20%20%20Observable.timer(800)%20%2F%2F%20debounce%5Cn%20%20%20%20%20%20%20%20.takeUntil(action%24.ofType(ActionTypes.CLEARED_SEARCH_RESULTS))%5Cn%20%20%20%20%20%20%20%20.mergeMap(()%20%3D%3E%20Observable.merge(%5Cn%20%20%20%20%20%20%20%20%20%20Observable.of(replace(%60%3Fq%3D%24%7Bq%7D%60))%2C%5Cn%20%20%20%20%20%20%20%20%20%20ajax.getJSON(%60https%3A%2F%2Fapi.github.com%2Fsearch%2Fusers%3Fq%3D%24%7Bq%7D%60)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20.map(res%20%3D%3E%20res.items)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20.map(receiveUsers)%5Cn%20%20%20%20%20%20%20%20))%5Cn%20%20%20%20)%3B%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D) code and having `q =>` put on a newline is adding another level of indentation, which means we're now 2 spaces closer to the wrap.  I couldn't find a ticket for this, but (if we have the space for it within the printWidth) would it be possible to have

```
    .switchMap(q =>
        Observable
```

Instead of

``` 
    .switchMap(
      q =>
        Observable
```

### PR DESCRIPTION
**Pull request by vjeux**
Fixes #274

### CODE REVIEW

**Comment by jlongster** [comment]
We used to have this but removed it. Unfortunately I can't trace it back to an issue. I think it was something to do with it creating something like this:

```
foo(foo(foo(foo(foo(foo(foo(foo(foo(foo(foo(foo(
  1
))))))))))))
```

It was that mixed in with some other syntax that didn't look right. I'll try to find the issue for it.

**Comment by vjeux** [comment]
Maybe we can check if there's a member expression one level down.

**Comment by jlongster** [comment]
I found it: https://github.com/jlongster/prettier/commit/6b582f808c2adcfbaf6c8971269c9235b3996d6a

Unfortunately that was Jan 9, before it was released, so there's not much explanation about it.

**Comment by jlongster** [comment]
I'm about confused how this is related to #274. That's about defining an arrow function and passing it as an argument, not a `CallExpression`.

**Comment by vjeux** [comment]
This is a MemberExpression chain but the top expression IS a CallExpression.

**Comment by jlongster** [comment]
Ah ok. I'm fine merging this and seeing any potential fallouts. People can complain if it causes weird formatting somewhere else and then we can document it.

**Pull request merged**
