### PR TITLE
Align boolean inside of arrow functions

### PR DESCRIPTION
**Pull request by vjeux**
We already do it for if/... but it looks weird for arrow function body.

### CODE REVIEW

**Comment by jlongster** [comment]
I'm beginning to think that the top-level binary expression should not indent it's "tail". It seems like we should go the opposite direction and do it by default, but special case it for things like variable declarations. What do you think?

**Comment by jlongster** [comment]
Although, there are several cases where we do want to indent them:

```
{
  prop: foo &&
    bar
}

foo
  ? bar &&
      baz
  : false
```

Not sure if we can determine when to do this or not easily.

**Comment by vjeux** [comment]
If you look at my original attempt, I tried doing it the other way and the code was getting super crazy. Whitelisting the places where we don't want to indent turned out to be way simpler.

**Comment by bakkot** [comment]
Drive-by comment - I would think that the second line of a binary expression would be indented past the first iff the first line was not on its own line.

For example:

```js
x = a
  && b; // indent

({
  x : a
    && b // indent
});

foo(
  a
  && b // no indent
);

a
&& b; // no indent
```

etc.

Doesn't require any special casing.

(Sorry if this is discussed elsewhere.)

**Pull request merged**
