### PR TITLE
Do not put \n inside of empty object method bodies

### LINKED ISSUE #703: Empty function object shorthand should not expand
```js
a = { f() {} }
```

turns into

```js
a = {
  f() {
  }
};
```

We don't expand empty functions, we should expand those either.

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22a%20%3D%20%7B%20f()%20%7B%7D%20%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

### PR DESCRIPTION
**Pull request by vjeux**
Fixes #703

### CODE REVIEW

**Comment by bakkot** [comment]
Also `ClassMethod`, maybe?

**Comment by vjeux** [comment]
@bakkot good idea!

**Comment by vjeux** [comment]
Updated with `ClassMethod`

**Comment by jlongster** [comment]
Looks good to me, thanks!

**Pull request merged**
